[package]
name = "scottricity/basictycoon"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

Red = "red-blox/red@^2.0.0"

##Red Utils
Fetch = "red-blox/fetch@^2.0.0"
Guard = "red-blox/guard@^1.0.0"

Cmdr = "evaera/cmdr@^1.12.0"
Promise = "evaera/promise@^4.0.0"
ProfileService = "scottricity/profileservice@^0.2.0"
ReplicaService = "scottricity/replicaservice@^0.2.0"

#UI Framework
TopbarPlus = "scottricity/topbarplus@1.1.0"
Fusion = "elttob/fusion@0.2.0"

Knit = "sleitnick/knit@1.5.3"

##RbxUtil
Comm = "sleitnick/comm@0.3.2"
Component = "sleitnick/component@2.4.8"
Concur = "sleitnick/concur@0.1.2"	
EnumList = "sleitnick/enum-list@2.1.0"	
Input = "sleitnick/input@2.2.1"	
Loader = "sleitnick/loader@2.0.0"	
Log = "sleitnick/log@0.1.1"	
Net = "sleitnick/net@0.1.0"	
Option = "sleitnick/option@1.0.5"
PID = "sleitnick/pid@1.1.0"
Quaternion = "sleitnick/quaternion@0.2.3"
Sequent = "sleitnick/sequent@0.1.0"
Ser = "sleitnick/ser@1.0.5"
Shake = "sleitnick/shake@0.1.7"
Signal = "sleitnick/signal@2.0.1"
Silo = "sleitnick/silo@0.1.2"
Streamable = "sleitnick/streamable@1.2.4"
Symbol = "sleitnick/symbol@2.0.1"
TableUtil = "sleitnick/table-util@1.2.1"
TaskQueue = "sleitnick/task-queue@1.0.0"
Timer = "sleitnick/timer@1.1.2"
Tree = "sleitnick/tree@1.1.0"
Trove = "sleitnick/trove@1.1.0"
WaitFor = "sleitnick/wait-for@1.0.0"